sudo: required
language: generic
services: docker

script:
  # We use the docker image from https://hub.docker.com/r/stevend32908324820/latexarchlinux
  - docker pull stevend32908324820/latexarchlinux
  # Fix permissions
  - sudo chmod 777 $TRAVIS_BUILD_DIR
  # Compiling only main.tex:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind stevend32908324820/latexarchlinux /bin/sh -c "tectonic main.tex"

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: main.pdf
  on:
    tags: false
    branch: master
